### ISSUE TITLE
Incorrect loading of history

### ISSUE THREAD

**Issue by jonpage** [bentut/udaman#10]
An example of this issue:
VAJPCNOLNS@HI.M
series/9889
data_source/21275 says it loaded today and that it has data up through 2014-02-01, even though the history file ends on Jan 2011.

**Comment by jonpage** [comment]
![screen shot 2014-04-16 at 4 25 13 pm](https://cloud.githubusercontent.com/assets/1771239/2727516/8b3d95ba-c5d7-11e3-92e3-52f09da4dc6e.png)

**Comment by bentut** [comment]
This was fixed by commit 35f9a663695f21a9b83a5706a4837ee7d46a3561
